// user
export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_ACCESS_TOKEN = 'UPDATE_ACCESS_TOKEN'
export const UPDATE_REFRESH_TOKEN = 'UPDATE_REFRESH_TOKEN'

// contacts
export const ADD_CONTACT = 'ADD_CONTACT'
export const CLEAR_CONTACT = 'CLEAR_CONTACT'
export const REMOVE_CONTACT = 'REMOVE_CONTACT'
export const REFRESH_CONTACTS = 'REFRESH_CONTACTS'

// messages
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE'
export const ADD_INVITATION = 'ADD_INVITATION'
export const CLEAR_INVITATION = 'CLEAR_INVITATION'
export const REMOVE_INVITATION = 'REMOVE_INVITATION'
